//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFrameWork.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
    
        public virtual ICollection<Student> Student { get; set; }
    }
}
